# Generated by Django 5.0.4 on 2024-04-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_todo_user_alter_todo_title_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='todos',
        ),
        migrations.AddField(
            model_name='todo',
            name='todoList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.todolist'),
        ),
    ]
